apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: label-pods
spec:
  resources:
  - apiVersion: windkube.com/v1
    resource: labels
  - apiVersion: apps/v1
    resource: deployments
  hooks:
    sync:
      webhook:
        url: http://192.168.116.221:9091/labeler # http://labeler.labeler/label
        timeout: 10s
