apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: labels.windkube.com
spec:
  group: windkube.com
  names:
    kind: Label
    plural: labels
    singular: label
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              label:
                type: string
    subresources:
     status: {}
